# Keep these alphabetical
AllCops:
  CacheRootDirectory: tmp
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - template/vendor/**/*
    - projects/**/*

Layout/LineLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AssignmentInCondition:
  Enabled: false

Metrics:
   Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SpecialGlobalVars:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/EmptyElse:
  Enabled: false

# suggests ugly "\n#{<<~MSG.gsub(/^/, "  ")}"
Style/StringConcatenation:
  Enabled: false

# using this a bunch in tests
Style/GlobalStdStream:
  Enabled: false

# new style looks sus and breaks old editors
Naming/BlockForwarding:
  Enabled: false

# TODO: fix
Lint/ConstantDefinitionInBlock:
  Enabled: false

# ignore_404 is fine
Naming/VariableNumber:
  Enabled: false

# omitting keys breaks old editors and looks funky
Style/HashSyntax:
  Enabled: false

# ENV["FOO"] is just fine
Style/FetchEnvVar:
  Enabled: false

# returning nil is more explicit
Style/NilLambda:
  Enabled: false

# makes structure more readable
Style/SoleNestedConditional:
  Enabled: false

# should be fine
Lint/FloatComparison:
  Enabled: false

# TODO: fix
Lint/NoReturnInBeginEndBlocks:
  Enabled: false

# suggestion breaks the code
Style/EvalWithLocation:
  Enabled: false

# either way works fine
Layout/LineContinuationLeadingSpace:
  Enabled: false

# TODO: fix
Layout/LineEndStringConcatenationIndentation:
  Enabled: false

# often more expressive to have multiple loops
Style/CombinableLoops:
  Enabled: false

# TODO: fix
Lint/NonAtomicFileOperation:
  Enabled: false

# on purpose
Lint/EmptyBlock:
  Enabled: false

# TODO: fix
Style/RedundantStringEscape:
  Enabled: false

# often makes logic more readable
Style/RedundantParentheses:
  Enabled: false

# often more readable
Style/ArgumentsForwarding:
  Enabled: false

# sometimes necessary
Style/SafeNavigationChainLength:
  Enabled: false
